### PR TITLE
add FromList

### PR DESCRIPTION
**Pull request by deemp**
add the FromList type family that converts a list of Symbols into a Symbol

### CODE REVIEW

**Comment by deemp** [comment]
@kcsongor, could you please review?

**Comment by kcsongor** [comment]
Thanks @deemp! The motivation for this function is a little unclear to me, it looks like it's doing two things: appends a list of symbols together, and ensures they are all ASCII? I guess what's not clear is why the extra check is necessary, and whether it would be better as a separate function.

**Comment by deemp** [comment]
If a user incidentally adds a non-ASCII character into the list, this character will be detected. Thus the user won't be able to construct a non-ASCII symbol and convert it into a list later.

I decided to use the DRY approach. Not sure if it adds a lot of overhead.

**Comment by deemp** [comment]
Hi, @kcsongor! changed the PR a bit. Please, review.

- Split FromList into separate functions
- `Exposed Data.Symbol.Ascii.Internal` . It contains several functions that library users may want to import if users accept the risks of relying on an internal module.
- Updated the package version (updated the minor version as this PR adds the new functionality without breaking changes).

I used `symbols` + FromList in `servant-named` . When https://github.com/haskell-servant/servant/pull/1678) is merged, users should be able to get all dependencies from Hackage. So, when this PR is OK, could you please upload your package to Hackage?

**Comment by deemp** [comment]
Btw, since base-4.16.0.0, there's [UnconsSymbol](https://hackage.haskell.org/package/base-4.16.0.0/docs/GHC-TypeLits.html#t:UnconsSymbol), `ConsSymbol`, `CmpChar`. These functions work for `Char`s, not necessarily ASCII ones.

A good example of usage of such functions is https://github.com/dmjio/typed-interpolation.

**Pull request closed without merging**
