### PR TITLE
Refactor Head and ToList type-families

### PR DESCRIPTION
**Pull request by phadej**
- I tried to add `DEL` to ascii set...
- and ended up rewriting ToList
- IMHO this is less "clever" design, with the same log2 cost
- I tested this with `overloaded`

EDIT: I changed `Tree` to contain a result in `Leaf`.
- I think this is simpler, as the leaf tells the result
- optionally one could track the lower-bound while traversing the tree, and return it
- it's a trade-off between "one less/more parameter for type-families" vs "bigger/smaller `Chars`"; I think this way is better as the `Leaf` node needs to be there anyway.

### CODE REVIEW

**Comment by phadej** [comment]
I’ll will make own small refactor in addition...

**Comment by phadej** [comment]
@kcsongor I made slightly different implementation, and I'm quite happy with the result. What do you think?

**Comment by kcsongor** [comment]
This looks great! Thanks a lot for making the code  less hacky :) if it's not too much hassle, could you please format the search tree so it's a little easier to look at?

**Comment by phadej** [comment]
@kcsongor done

**Pull request merged**
